packages:
  - "zones/*"
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@timmbr/ui@1.5.0"
  - "@timmbr/motion@1.2.1"
  - "@timmbr/theme@1.3.0"
  - "@timmbr/icons@1.3.0"
  - "@timmbr/hooks@1.0.0"
  - "@timmbr/utils@1.3.0"
  - "@timmbr/auth@1.0.0"
